### ISSUE TITLE
Error when running extract_interpretations for NP/Z

### ISSUE THREAD

**Issue by forrestdavis** [lauraina/syntactic-uncertainty-LMs#1]
Hi, 

I'm working with an undergrad who is interested in your work. We are trying to recreate the NP/Z results, and there seems to be an issue with the extract_interpretations code. After running:

``python src/extract_interpretations.py --lm GPT2 --ambiguity NP-Z``

I get an error with the variable post_disambiguation which isn't defined in the script.

> Traceback (most recent call last):
>  File "src/extract_interpretations.py", line 262, in <module>
>    incorrect_ambig = evaluate_original_sentences(data_dir, data_type=ambiguity, parser=parser, ambig=True)
>  File "src/extract_interpretations.py", line 149, in evaluate_original_sentences
>    interpretation, detailed = get_interpretation(tokens, parse, pos,  locus_ambiguity, data=data_type, postlocus_cue = postlocus_cue, with_postlocus_cue= True, parser = parser)
>  File "src/extract_interpretations.py", line 83, in get_interpretation
>    if post_disambiguation:
> NameError: name 'post_disambiguation' is not defined``

A similar issue would later arise with index_disambiguator on line 84, which is also not defined. 

Thanks!

**Comment by lauraina** [comment]
Thank you for bringing this up! 

Both `post_disambiguation`and `index_disambiguator` were old variable names and those occurrences that you mentioned were not renamed as they should have (`with_postlocus_cue` and `index_postlocus_cue`, respectively). This should be fixed with the latest commit I did now. Let me know if there are still some issues!

**Comment by forrestdavis** [comment]
Thank you for the quick response! 

Could I also check which version of allennlp you are using with this repo?

**Comment by lauraina** [comment]
I've been using the 0.9.0 version (latest when I started the project but not anymore). 

If you notice, in `src/parse_sentences.py` (line 110), I load a specific instance of the dependency parser from a path. This isn't the latest version, but - if I remember this correctly - at some point during my project AllenNLP uploaded a new instance of the parser and it seemed to have issues (outputting many generic DEP labels; you can see this at the demo https://demo.allennlp.org/dependency-parsing). So I just kept on using the previous parser which was working well. I think it was for this reason that I did not upgrade the AllenNLP library (it was probably not working otherwise, but I don't remember the details). I hope this helps!

**Comment by forrestdavis** [comment]
That does help. I had a newer version on my end and was getting similar issues to what you describe. I'll use the older version and that specific version of the parser. 

Thank you again! I really enjoyed this paper!
